Gavin_Ostheimer_Book_App/Controllers/SaleController.cs
using Gavin_Ostheimer_Book_App.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gavin_Ostheimer_Book_App.Controllers
{
    public class SaleController : Controller
    {
        private ISaleRepository repo { get; set; }
        private Basket basket { get; set; }

        public SaleController(ISaleRepository temp, Basket ba)
        {
            repo = temp;
            basket = ba;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Sale());
        }

        [HttpPost]
        public IActionResult Checkout(Sale sale)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                sale.Lines = basket.Items.ToArray();
                repo.SaveSale(sale);
                basket.ClearBasket();

                return RedirectToPage("/SaleCompleted");
            }
            else
            {
                return View();
            }
        }
    }
}

Gavin_Ostheimer_Book_App/Pages/AddBooks.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Gavin_Ostheimer_Book_App.Infrastructure;
using Gavin_Ostheimer_Book_App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Gavin_Ostheimer_Book_App.Pages
{
    public class AddBooksModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }
        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }

        public AddBooksModel (IBookstoreRepository temp, Basket ba)
        {
            repo = temp;
            basket = ba;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new {ReturnUrl = returnUrl});
        }
    }
}

Gavin_Ostheimer_Book_App/Pages/SaleCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Gavin_Ostheimer_Book_App.Pages
{
    public class SaleCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Gavin_Ostheimer_Book_App/Pages/AddBooks.cshtml
@page
@model Gavin_Ostheimer_Book_App.Pages.AddBooksModel
@{
}

<h2>Your basket</h2>

<table class="table-bordered table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach(var i in Model.basket.Items)
            {
        <tr>
            <td>@i.Book.Title</td>
            <td>@i.Quantity</td>
            <td>@((i.Book.Price).ToString("c"))</td>
            <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>

            <td class="text-center">
                <form method="post" asp-page-handler="Remove">
                    <input type="hidden" name="bookId" value="@i.Book.BookId" />
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                </form>
            </td>

        </tr>
            }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="Sale" asp-action="Checkout" >Checkout</a>
</div>

Gavin_Ostheimer_Book_App/Pages/SaleCompleted.cshtml
@page
@model Gavin_Ostheimer_Book_App.Pages.SaleCompletedModel
@{
}

<div class="text-center">
    <h2>Thanks! Your order has been completed!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Gavin_Ostheimer_Book_App/Pages/_AddBooksLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        Gavin's Bookstore
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>