Gavin_Ostheimer_Book_App/Components/BasketSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Gavin_Ostheimer_Book_App.Models; // Replace this with the appropriate namespace that contains your "Basket" model

namespace Gavin_Ostheimer_Book_App.Components
{
    public class BasketSummaryViewComponent : ViewComponent
    {
        private Basket basket;

        public BasketSummaryViewComponent(Basket basketService)
        {
            basket = basketService;
        }

        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Gavin_Ostheimer_Book_App/Components/TypesViewComponent.cs
using Gavin_Ostheimer_Book_App.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gavin_Ostheimer_Book_App.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["Category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Gavin_Ostheimer_Book_App/Views/Shared/BookSummary.cshtml
@{
}

@model Book


<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>Price: @Model.Price</small>
            </span>
        </h4>
    </div>
    <ul>
        <li class="card-text p-1">Author: @Model.Author</li>
        <li class="card-text p-1">Publisher: @Model.Publisher</li>
        <li class="card-text p-1">ISBN: @Model.Isbn</li>
        <li class="card-text p-1">Classification: @Model.Classification</li>
        <li class="card-text p-1">Category: @Model.Category</li>
        <li class="card-text p-1">Number of Pages: @Model.PageCount</li>
    </ul>

    <form method="post" asp-page="/AddBooks">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type ="hidden" name="returnURL" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>

    </form>

</div>

Gavin_Ostheimer_Book_App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Menu</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="bg-dark text-white p-2">
        <div class="container">
            <!-- Add container div -->
            <div class="row">
                <div class="col-md-6">
                    <!-- Change col to col-md-6 -->
                    <span class="navbar-brand ml-2">Gavin's Bookstore</span>
                </div>
                <div class="col-md-6 text-right">
                    <!-- Add this div for basket summary -->
                    <vc:basket-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <br />
    <br />
</body>

<footer class="bg-dark text-white p-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="text-danger mb-4">The Hunt for Red October Movie</h2>
            </div>
        </div>

        <!-- Audio Implementation-->
        <div class="row">
            <div class="col-md-6">
                <h4 class="text-light mb-3">Listen to a famous audio clip from the movie:</h4>
                <div class="mb-4">
                    <audio controls="controls" class="embed-responsive-item">
                        <source src="~/audio/revolution.mp3" type="audio/mpeg" />
                    </audio>
                </div>
            </div>
            <div class="col-md-6">
                <h4 class="text-light mb-3">Watch an advertisement for the movie:</h4>
                <div class="mb-4">
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#videoModal">Watch Video</button>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Video Modal -->
<div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="videoModalLabel">Advertisement for The Hunt for Red October Movie</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="embed-responsive embed-responsive-16by9 mb-4">
                    <video controls="controls" class="embed-responsive-item">
                        <source src="~/video/1884.mp4" type="video/mp4" />
                    </video>
                </div>
            </div>
        </div>
    </div>
</div>



</html>